import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case english = "en"
    case russian = "ru"
    case spanish = "es"
    case german = "de"
    case french = "fr"
    case chineseSimplified = "zh-Hans"

    var id: String { rawValue }

    var pickerTitle: String {
        switch self {
        case .system: return L("language.system")
        case .english: return "English"
        case .russian: return "Russian"
        case .spanish: return "Español"
        case .german: return "Deutsch"
        case .french: return "Français"
        case .chineseSimplified: return "简体中文"
        }
    }
}

private enum LocalizationTable {
    static let values: [String: [String: String]] = [
        "en": [
            "app.title": "ESP32 DFU",
            "header.title": "Legacy DFU for ESP32",
            "status.scan_on": "BLE Scan On",
            "status.scan_off": "BLE Scan Off",
            "status.dfu_running": "DFU Running",
            "status.idle": "Idle",
            "device.not_selected": "No device selected",
            "firmware.not_selected": "No file selected",
            "device.subtitle": "Select ESP32 in DFU mode",
            "firmware.subtitle": "Select firmware.bin",
            "button.devices": "Devices",
            "button.file": "File",
            "button.start_dfu": "Start DFU",
            "button.cancel": "Cancel",
            "timeline.title": "Firmware stages",
            "picker.title": "Device selection",
            "picker.scan_timeout": "Scan will stop in %d sec",
            "settings.title": "Settings",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "BLE Scanning",
            "settings.section.behavior": "Behavior",
            "settings.section.language": "Language",
            "settings.section.info": "Info",
            "settings.prn": "PRN: %d",
            "settings.mtu": "MTU: %d",
            "settings.scan_seconds": "Scan duration: %d sec",
            "settings.auto_reconnect": "Auto reconnect",
            "settings.keep_screen_awake": "Keep screen awake",
            "settings.profile": "Profile: Nordic Legacy DFU",
            "settings.target": "Target: ESP32 BLE OTA",
            "settings.language_picker": "App language",
            "language.system": "System",
            "msg.select_device_file": "Select a device and firmware file",
            "msg.scan_finished_found": "Scan finished: found %d devices",
            "msg.scan_in_progress": "Scanning BLE devices (up to %d sec)",
            "msg.need_device_and_firmware": "You need to select a device and a firmware file",
            "msg.bluetooth_unavailable": "Bluetooth is off or unavailable",
            "msg.unable_open_firmware": "Unable to open firmware file: %@",
            "msg.cancelled": "Operation cancelled by user",
            "msg.ble_retry": "BLE disconnected. Retry %d/%d",
            "msg.dfu_error": "DFU failed: %@",
            "stage.idle.title": "Ready for DFU",
            "stage.idle.details": "Select a device and firmware file",
            "stage.scanning.title": "Scanning devices",
            "stage.scanning.details": "Scanning nearby BLE devices",
            "stage.connecting.title": "Connecting",
            "stage.connecting.details": "Establishing stable BLE connection",
            "stage.bootloader.title": "Bootloader switch",
            "stage.bootloader.details": "Switching device to update mode",
            "stage.init.title": "Init packet",
            "stage.init.details": "Sending DFU metadata",
            "stage.fw.title": "Firmware upload",
            "stage.fw.details": "Sending firmware binary over BLE",
            "stage.validate.title": "Validation",
            "stage.validate.details": "Checking firmware size and integrity",
            "stage.activate.title": "Activate and reboot",
            "stage.activate.details": "Switching OTA slot and rebooting",
            "stage.completed.title": "Update complete",
            "stage.completed.details": "Device is running new firmware",
            "stage.failed.title": "Update failed",
            "stage.failed.details": "Check connection and retry",
            "device.unknown": "Unknown ESP32"
        ],
        "ru": [
            "app.title": "ESP32 DFU",
            "header.title": "Legacy DFU for ESP32",
            "status.scan_on": "BLE Scan On",
            "status.scan_off": "BLE Scan Off",
            "status.dfu_running": "DFU Running",
            "status.idle": "Idle",
            "device.not_selected": "No device selected",
            "firmware.not_selected": "No file selected",
            "device.subtitle": "Select ESP32 in DFU mode",
            "firmware.subtitle": "Select firmware.bin",
            "button.devices": "Devices",
            "button.file": "File",
            "button.start_dfu": "Start DFU",
            "button.cancel": "Cancel",
            "timeline.title": "Firmware stages",
            "picker.title": "Device selection",
            "picker.scan_timeout": "Scan will stop in %d sec",
            "settings.title": "Settings",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "BLE Scanning",
            "settings.section.behavior": "Behavior",
            "settings.section.language": "Language",
            "settings.section.info": "Info",
            "settings.prn": "PRN: %d",
            "settings.mtu": "MTU: %d",
            "settings.scan_seconds": "Scan duration: %d sec",
            "settings.auto_reconnect": "Auto reconnect",
            "settings.keep_screen_awake": "Keep screen awake",
            "settings.profile": "Profile: Nordic Legacy DFU",
            "settings.target": "Target: ESP32 BLE OTA",
            "settings.language_picker": "App language",
            "language.system": "System",
            "msg.select_device_file": "Select a device and firmware file",
            "msg.scan_finished_found": "Scan finished: found %d devices",
            "msg.scan_in_progress": "Scanning BLE devices (up to %d sec)",
            "msg.need_device_and_firmware": "You need to select a device and a firmware file",
            "msg.bluetooth_unavailable": "Bluetooth is off or unavailable",
            "msg.unable_open_firmware": "Unable to open firmware file: %@",
            "msg.cancelled": "Operation cancelled by user",
            "msg.ble_retry": "BLE disconnected. Retry %d/%d",
            "msg.dfu_error": "DFU failed: %@",
            "stage.idle.title": "Ready for DFU",
            "stage.idle.details": "Select a device and firmware file",
            "stage.scanning.title": "Scanning devices",
            "stage.scanning.details": "Scanning nearby BLE devices",
            "stage.connecting.title": "Connecting",
            "stage.connecting.details": "Establishing stable BLE connection",
            "stage.bootloader.title": "Bootloader switch",
            "stage.bootloader.details": "Switching device to update mode",
            "stage.init.title": "Init packet",
            "stage.init.details": "Sending DFU metadata",
            "stage.fw.title": "Firmware upload",
            "stage.fw.details": "Sending firmware binary over BLE",
            "stage.validate.title": "Validation",
            "stage.validate.details": "Checking firmware size and integrity",
            "stage.activate.title": "Activate and reboot",
            "stage.activate.details": "Switching OTA slot and rebooting",
            "stage.completed.title": "Update complete",
            "stage.completed.details": "Device is running new firmware",
            "stage.failed.title": "Update failed",
            "stage.failed.details": "Check connection and retry",
            "device.unknown": "Unknown ESP32"
        ],
        "es": [
            "app.title": "ESP32 DFU",
            "header.title": "Legacy DFU para ESP32",
            "device.not_selected": "Dispositivo no seleccionado",
            "firmware.not_selected": "Archivo no seleccionado",
            "device.subtitle": "Seleccione ESP32 en modo DFU",
            "firmware.subtitle": "Seleccione firmware.bin",
            "button.devices": "Dispositivos",
            "button.file": "Archivo",
            "button.start_dfu": "Iniciar DFU",
            "button.cancel": "Cancelar",
            "timeline.title": "Etapas del firmware",
            "picker.title": "Selección de dispositivo",
            "picker.scan_timeout": "La búsqueda termina en %d s",
            "status.scan_on": "Escaneo BLE activo",
            "status.scan_off": "Escaneo BLE detenido",
            "status.dfu_running": "DFU en curso",
            "status.idle": "En espera",
            "settings.title": "Configuración",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "Escaneo BLE",
            "settings.section.behavior": "Comportamiento",
            "settings.section.language": "Idioma",
            "settings.section.info": "Información",
            "settings.prn": "PRN: %d",
            "settings.mtu": "MTU: %d",
            "settings.scan_seconds": "Duración del escaneo: %d s",
            "settings.auto_reconnect": "Reconexión automática",
            "settings.keep_screen_awake": "Mantener pantalla activa",
            "settings.profile": "Perfil: Nordic Legacy DFU",
            "settings.target": "Objetivo: ESP32 BLE OTA",
            "settings.language_picker": "Idioma de la app",
            "language.system": "Sistema",
            "msg.select_device_file": "Seleccione dispositivo y archivo",
            "msg.scan_finished_found": "Búsqueda finalizada: %d dispositivos encontrados",
            "msg.scan_in_progress": "Escaneando dispositivos BLE (hasta %d s)",
            "msg.need_device_and_firmware": "Debe seleccionar dispositivo y archivo de firmware",
            "msg.bluetooth_unavailable": "Bluetooth está apagado o no disponible",
            "msg.unable_open_firmware": "No se pudo abrir el firmware: %@",
            "msg.cancelled": "Operación cancelada por el usuario",
            "msg.ble_retry": "BLE desconectado. Reintento %d/%d",
            "msg.dfu_error": "DFU falló: %@",
            "stage.idle.title": "Listo para DFU",
            "stage.idle.details": "Seleccione un dispositivo y un archivo de firmware",
            "stage.scanning.title": "Buscando dispositivos",
            "stage.scanning.details": "Escaneando dispositivos BLE cercanos",
            "stage.connecting.title": "Conectando",
            "stage.connecting.details": "Estableciendo conexión BLE estable",
            "stage.bootloader.title": "Cambio a bootloader",
            "stage.bootloader.details": "Pasando el dispositivo al modo de actualización",
            "stage.init.title": "Paquete de inicio",
            "stage.init.details": "Enviando metadatos DFU",
            "stage.fw.title": "Carga de firmware",
            "stage.fw.details": "Enviando el binario por BLE",
            "stage.validate.title": "Validación",
            "stage.validate.details": "Comprobando tamaño e integridad",
            "stage.activate.title": "Activar y reiniciar",
            "stage.activate.details": "Cambiando slot OTA y reiniciando",
            "stage.completed.title": "Actualización completada",
            "stage.completed.details": "El dispositivo ejecuta el nuevo firmware",
            "stage.failed.title": "Error de actualización",
            "stage.failed.details": "Verifique la conexión e inténtelo de nuevo",
            "device.unknown": "ESP32 desconocido"
        ],
        "de": [
            "app.title": "ESP32 DFU",
            "header.title": "Legacy DFU für ESP32",
            "device.not_selected": "Kein Gerät ausgewählt",
            "firmware.not_selected": "Keine Datei ausgewählt",
            "device.subtitle": "ESP32 im DFU-Modus auswählen",
            "firmware.subtitle": "firmware.bin auswählen",
            "button.devices": "Geräte",
            "button.file": "Datei",
            "button.start_dfu": "DFU starten",
            "button.cancel": "Abbrechen",
            "timeline.title": "Firmware-Stufen",
            "picker.title": "Geräteauswahl",
            "picker.scan_timeout": "Suche endet in %d Sek.",
            "status.scan_on": "BLE-Scan aktiv",
            "status.scan_off": "BLE-Scan gestoppt",
            "status.dfu_running": "DFU läuft",
            "status.idle": "Bereit",
            "settings.title": "Einstellungen",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "BLE-Scan",
            "settings.section.behavior": "Verhalten",
            "settings.section.language": "Sprache",
            "settings.section.info": "Info",
            "settings.prn": "PRN: %d",
            "settings.mtu": "MTU: %d",
            "settings.scan_seconds": "Scan-Dauer: %d Sek.",
            "settings.auto_reconnect": "Automatisch neu verbinden",
            "settings.keep_screen_awake": "Bildschirm aktiv halten",
            "settings.profile": "Profil: Nordic Legacy DFU",
            "settings.target": "Ziel: ESP32 BLE OTA",
            "settings.language_picker": "App-Sprache",
            "language.system": "System",
            "msg.select_device_file": "Gerät und Datei auswählen",
            "msg.scan_finished_found": "Suche beendet: %d Geräte gefunden",
            "msg.scan_in_progress": "BLE-Geräte werden gescannt (bis %d Sek.)",
            "msg.need_device_and_firmware": "Gerät und Firmware-Datei müssen ausgewählt werden",
            "msg.bluetooth_unavailable": "Bluetooth ist ausgeschaltet oder nicht verfügbar",
            "msg.unable_open_firmware": "Firmware-Datei konnte nicht geöffnet werden: %@",
            "msg.cancelled": "Vorgang vom Benutzer abgebrochen",
            "msg.ble_retry": "BLE-Verbindung getrennt. Wiederholung %d/%d",
            "msg.dfu_error": "DFU fehlgeschlagen: %@",
            "stage.idle.title": "Bereit für DFU",
            "stage.idle.details": "Wählen Sie ein Gerät und eine Firmware-Datei",
            "stage.scanning.title": "Geräte werden gesucht",
            "stage.scanning.details": "BLE-Geräte in der Nähe werden gescannt",
            "stage.connecting.title": "Verbinden",
            "stage.connecting.details": "Stabile BLE-Verbindung wird aufgebaut",
            "stage.bootloader.title": "Bootloader-Wechsel",
            "stage.bootloader.details": "Gerät wird in den Update-Modus versetzt",
            "stage.init.title": "Init-Paket",
            "stage.init.details": "DFU-Metadaten werden gesendet",
            "stage.fw.title": "Firmware-Upload",
            "stage.fw.details": "Firmware-Binärdatei wird per BLE gesendet",
            "stage.validate.title": "Validierung",
            "stage.validate.details": "Größe und Integrität werden geprüft",
            "stage.activate.title": "Aktivieren und Neustart",
            "stage.activate.details": "OTA-Slot wird umgeschaltet und neu gestartet",
            "stage.completed.title": "Update abgeschlossen",
            "stage.completed.details": "Gerät läuft mit neuer Firmware",
            "stage.failed.title": "Update fehlgeschlagen",
            "stage.failed.details": "Verbindung prüfen und erneut versuchen",
            "device.unknown": "Unbekannter ESP32"
        ],
        "fr": [
            "app.title": "ESP32 DFU",
            "header.title": "Legacy DFU pour ESP32",
            "device.not_selected": "Appareil non sélectionné",
            "firmware.not_selected": "Fichier non sélectionné",
            "device.subtitle": "Sélectionnez ESP32 en mode DFU",
            "firmware.subtitle": "Sélectionnez firmware.bin",
            "button.devices": "Appareils",
            "button.file": "Fichier",
            "button.start_dfu": "Démarrer DFU",
            "button.cancel": "Annuler",
            "timeline.title": "Étapes du firmware",
            "picker.title": "Sélection de l'appareil",
            "picker.scan_timeout": "La recherche se termine dans %d s",
            "status.scan_on": "Scan BLE actif",
            "status.scan_off": "Scan BLE arrêté",
            "status.dfu_running": "DFU en cours",
            "status.idle": "En attente",
            "settings.title": "Réglages",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "Scan BLE",
            "settings.section.behavior": "Comportement",
            "settings.section.language": "Langue",
            "settings.section.info": "Info",
            "settings.prn": "PRN : %d",
            "settings.mtu": "MTU : %d",
            "settings.scan_seconds": "Durée du scan : %d s",
            "settings.auto_reconnect": "Reconnexion automatique",
            "settings.keep_screen_awake": "Garder l'écran actif",
            "settings.profile": "Profil : Nordic Legacy DFU",
            "settings.target": "Cible : ESP32 BLE OTA",
            "settings.language_picker": "Langue de l'app",
            "language.system": "Système",
            "msg.select_device_file": "Sélectionnez un appareil et un fichier",
            "msg.scan_finished_found": "Recherche terminée : %d appareils trouvés",
            "msg.scan_in_progress": "Scan des appareils BLE (jusqu'à %d s)",
            "msg.need_device_and_firmware": "Vous devez sélectionner un appareil et un fichier firmware",
            "msg.bluetooth_unavailable": "Bluetooth est désactivé ou indisponible",
            "msg.unable_open_firmware": "Impossible d'ouvrir le firmware : %@",
            "msg.cancelled": "Opération annulée par l'utilisateur",
            "msg.ble_retry": "BLE déconnecté. Nouvelle tentative %d/%d",
            "msg.dfu_error": "Échec DFU : %@",
            "stage.idle.title": "Prêt pour DFU",
            "stage.idle.details": "Sélectionnez un appareil et un fichier firmware",
            "stage.scanning.title": "Recherche des appareils",
            "stage.scanning.details": "Scan des appareils BLE à proximité",
            "stage.connecting.title": "Connexion",
            "stage.connecting.details": "Établissement d'une connexion BLE stable",
            "stage.bootloader.title": "Passage en bootloader",
            "stage.bootloader.details": "Basculement de l'appareil en mode mise à jour",
            "stage.init.title": "Paquet d'initialisation",
            "stage.init.details": "Envoi des métadonnées DFU",
            "stage.fw.title": "Envoi du firmware",
            "stage.fw.details": "Transfert du binaire via BLE",
            "stage.validate.title": "Validation",
            "stage.validate.details": "Vérification de la taille et de l'intégrité",
            "stage.activate.title": "Activation et redémarrage",
            "stage.activate.details": "Bascule du slot OTA et redémarrage",
            "stage.completed.title": "Mise à jour terminée",
            "stage.completed.details": "L'appareil exécute le nouveau firmware",
            "stage.failed.title": "Échec de la mise à jour",
            "stage.failed.details": "Vérifiez la connexion et réessayez",
            "device.unknown": "ESP32 inconnu"
        ],
        "zh-Hans": [
            "app.title": "ESP32 DFU",
            "header.title": "ESP32 传统 DFU",
            "device.not_selected": "未选择设备",
            "firmware.not_selected": "未选择文件",
            "device.subtitle": "请选择 DFU 模式下的 ESP32",
            "firmware.subtitle": "请选择 firmware.bin",
            "button.devices": "设备",
            "button.file": "文件",
            "button.start_dfu": "开始 DFU",
            "button.cancel": "取消",
            "timeline.title": "固件阶段",
            "picker.title": "设备选择",
            "picker.scan_timeout": "%d 秒后结束扫描",
            "status.scan_on": "BLE 扫描中",
            "status.scan_off": "BLE 扫描已停止",
            "status.dfu_running": "DFU 进行中",
            "status.idle": "待机",
            "settings.title": "设置",
            "settings.section.dfu": "DFU",
            "settings.section.scan": "BLE 扫描",
            "settings.section.behavior": "行为",
            "settings.section.language": "语言",
            "settings.section.info": "信息",
            "settings.prn": "PRN：%d",
            "settings.mtu": "MTU：%d",
            "settings.scan_seconds": "扫描时长：%d 秒",
            "settings.auto_reconnect": "自动重连",
            "settings.keep_screen_awake": "保持屏幕常亮",
            "settings.profile": "配置：Nordic Legacy DFU",
            "settings.target": "目标：ESP32 BLE OTA",
            "settings.language_picker": "应用语言",
            "language.system": "跟随系统",
            "msg.select_device_file": "请选择设备和固件文件",
            "msg.scan_finished_found": "扫描结束：找到 %d 个设备",
            "msg.scan_in_progress": "正在扫描 BLE 设备（最多 %d 秒）",
            "msg.need_device_and_firmware": "请选择设备和固件文件",
            "msg.bluetooth_unavailable": "蓝牙已关闭或不可用",
            "msg.unable_open_firmware": "无法打开固件文件：%@",
            "msg.cancelled": "用户已取消操作",
            "msg.ble_retry": "BLE 已断开。重试 %d/%d",
            "msg.dfu_error": "DFU 失败：%@",
            "stage.idle.title": "准备 DFU",
            "stage.idle.details": "请选择设备和固件文件",
            "stage.scanning.title": "扫描设备",
            "stage.scanning.details": "正在扫描附近 BLE 设备",
            "stage.connecting.title": "连接中",
            "stage.connecting.details": "正在建立稳定的 BLE 连接",
            "stage.bootloader.title": "进入引导模式",
            "stage.bootloader.details": "将设备切换到更新模式",
            "stage.init.title": "初始化包",
            "stage.init.details": "正在发送 DFU 元数据",
            "stage.fw.title": "固件上传",
            "stage.fw.details": "通过 BLE 发送固件二进制",
            "stage.validate.title": "校验",
            "stage.validate.details": "检查固件大小和完整性",
            "stage.activate.title": "激活并重启",
            "stage.activate.details": "切换 OTA 分区并重启",
            "stage.completed.title": "更新完成",
            "stage.completed.details": "设备正在运行新固件",
            "stage.failed.title": "更新失败",
            "stage.failed.details": "请检查连接后重试",
            "device.unknown": "未知 ESP32"
        ]
    ]
}

private final class AppLocalizer {
    static let shared = AppLocalizer()

    private init() {}

    func translate(_ key: String, _ args: [CVarArg]) -> String {
        let languageCode = resolvedLanguageCode()
        let template = LocalizationTable.values[languageCode]?[key] ?? LocalizationTable.values["en"]?[key] ?? key
        guard !args.isEmpty else {
            return template
        }
        return String(format: template, locale: Locale(identifier: languageCode), arguments: args)
    }

    private func resolvedLanguageCode() -> String {
        let selected = UserDefaults.standard.string(forKey: "app.language") ?? AppLanguage.system.rawValue
        if selected != AppLanguage.system.rawValue,
           LocalizationTable.values[selected] != nil {
            return selected
        }

        for preferred in Locale.preferredLanguages {
            let lower = preferred.lowercased()
            if lower.hasPrefix("ru") { return "ru" }
            if lower.hasPrefix("es") { return "es" }
            if lower.hasPrefix("de") { return "de" }
            if lower.hasPrefix("fr") { return "fr" }
            if lower.hasPrefix("zh") { return "zh-Hans" }
            if lower.hasPrefix("en") { return "en" }
        }

        return "en"
    }
}

func L(_ key: String, _ args: CVarArg...) -> String {
    AppLocalizer.shared.translate(key, args)
}
